### ISSUE TITLE
EN -> RU Translation

### ISSUE THREAD

**Issue by ItsLeon15** [audiamus/AaxAudioConverter#102]
This isn't really an issue about the project but I was wondering if I could introduce Russian Language into the application?

Thanks

**Comment by audiamus** [comment]
Thank you very much for your suggestion. I guess you have done such a thing before. 

Are you familiar with the .Net environment, Windows Forms and its concept of multi-language support, resource files etc? And with Visual Studio?

(In the ideal case, the user manual would have to be translated, too. It's written with LibreOffice.)

You are also aware that translations need updates with almost every new version of the app? Because of that, I do not recommend to start translating at the moment because I am currently working on AAX Audio Converter 2 which shall add a direct download option for your books and also reshuffle much of the existing code.

> This isn't really an issue about the project 

So, I move it to the discussion section.
