### ISSUE TITLE
Chapters splitting in incorrect locations

### ISSUE THREAD

**Issue by Zelatrix** [audiamus/AaxAudioConverter#131]
I am trying to convert my audiobooks (which I have exported to single AAX files) into MP3. If I select the option to split it into files by chapter, so that a 9-chapter book has 9 files, it splits it into the right number of files, but the chapters are split in the wrong places. It says in the README that you can change this, but I don't see that option, and I want to split it so that each chapter is split in the same way as the timestamps on the Audible application. 

For example, The Witcher: Baptism of Fire has 9 chapters; the opening credits, an epigraph, chapters 1-7, and a bonus track. I would like it to split into these as they are on the Audible app, and not, for example, merge the epigraph and opening credits into chapter 1. 

How can I do this so that it's easier to manage my collection?

**Comment by audiamus** [comment]
We are in the hands of Audible here, where they set the chapters marks, as part of the meta data for the book. There are two possible sources for the chapter data: embedded in the original AAX file (or AAXC) or as separate json files. The latter you'll get if you download with the Audible Win10 app (while it is still working) or with Book Lib Connect. 

Both sources have chapter timings, the extra json files may also have explicit chapter names, if the book has such, not just numbers: Chapter 1, 2 3 etc. But again, this is dependent on Audible. If you run AAX Audio Converter with logging enabled, log level 3, the log will list both the embedded chapter data and the extra json data, if available.  

If the chapter time marks cut the audio mid-word, AAX Audio Converter can try to adjust the time mark, so that it falls into a short period of silence, ideally immediately before the narrator reads out the next chapter title. But if the chapter mark is misplaced and points to a position in the midst of a chapter, there is no way to correct this. I have several books in my own collection which fall into this unfortunate category.

If the chapter marks in your case are only slightly off, you can try to play with the chapter adjustment settings. See the AAX Audio Converter manual for this, [F1] or via the system menu. The manual is quite detailed and has several paragraphs on chapter handling. But again, if the chapter marks are totally wrong, we are out of luck.     

Theoretically you can also manipulate the chapters in the json file, it's plain text, but you will need an audio editor like Audacity to figure out the correct timings. And it will be a lot of work.

**Comment by Zelatrix** [comment]
> We are in the hands of Audible here, where they set the chapters marks, as part of the meta data for the book. There are two possible sources for the chapter data: embedded in the original AAX file (or AAXC) or as separate json files. The latter you'll get if you download with the Audible Win10 app (while it is still working) or with Book Lib Connect.

I don't understand why, though, if the times are set by Audible in the metadata, converting it using AAX Audio Converter is merging some of the chapters instead of splitting them according to the timestamps on the Audible app, which presumably correspond to the timestamps in the JSON files (which I don't see after running it through BookLibConnect)

**Comment by audiamus** [comment]
The log file will tell which chapter data sources are being used.

**Comment by Zelatrix** [comment]
What am I looking for in the log file that can tell me that?

**Comment by audiamus** [comment]
The `NamedChapters` setting will determine whether json chapters are looked for or not. All settings are listed in the log.
`[AaxAudioConverter.verifyActivationAndGetChapters] aax/aa chapters:` for the embedded chapters.
`[AudibleAppContentMetadata.getContentMetaChapters] content meta chapters:` for the json chapters. If the latter are listed, they would be used.

**Comment by Zelatrix** [comment]
I've looked in the log for that download and I can't see anything like this in there.

**Comment by audiamus** [comment]
Do you actually have the corresponding content_meta_ASIN.json file? It should be in the same folder as the .aax file. AAX Audio Converter extracts the ASIN from the .aax file name and looks for the json file with the same ASIN. When downloading with Book Lib Connect and exporting it, all related files will be placed in the export folder.

**Comment by Zelatrix** [comment]
I got that file, yes. What do I do with it?

**Comment by audiamus** [comment]
It should then be found in the log file, [see above](https://github.com/audiamus/AaxAudioConverter/issues/131#issuecomment-1094116819).

_Note: Logging in AAX Audio Converter must be enabled separately, see the AAX Audio Converter manual, chapter 4._

**Comment by Zelatrix** [comment]
OK, I got it to work. I'm just dumb. But I don't quite understand why not all my books are showing up when I scan with BookLibConnect

**Comment by audiamus** [comment]
OK, great.
