### ISSUE TITLE
activation code using aax converter

### ISSUE THREAD

**Issue by mikel1954** [audiamus/AaxAudioConverter#153]
I have used the aax converter to convert audible audiobooks to mp3 for years, without problems. But recently it refuses to convert the book; I get the "Activation error" message.  Usually this is rectified by signing into the Audible app which enables the converter to find the activation code, but I have done this without any success.  I have asked Audible for the activation code so that I can enter it manually, but they have not been able to help.  Any suggestions would be gratefully received.  Thank you.

**Comment by audiamus** [comment]
>  Usually this is rectified by signing into the Audible app which enables the converter to find the activation code, but I have done this without any success

As far as I know the Audible Win 10 app no longer works. It has been officially withdrawn, without a successor. I suggest to try [Book Lib Connect](https://github.com/audiamus/BookLibConnect) instead, my relatively new companion to AAX Audio Converter. Downloading with Book Lib Connect includes decryption. Then use AAX Audio Converter for tailoring your audiobook to your needs.

**Comment by mikel1954** [comment]
Hi audiamus, thanks for your very prompt & helpful response.  I understand that the  Audible app has been discontinued, but it has been replaced by the Audible Sync App which I have also installed and activated.  In the past, this has worked well, but recently this has not worked either.  I tried uninstalling the aax audioconverter and reinstalling it, but no success.  However, I will try the Book Lib Connect as you suggest, and see how I get on.  Thanks again for your help.

**Comment by mikel1954** [comment]
Hi audiamus.  I installed Book Lib Connect but it would not allow me to access my audible account.

**Comment by mikel1954** [comment]
Hi audiamus, just to let you know I have installed Book Lib Connect, and despite some initial problems, it seems to work very well.  I can now convert them to mp3 using aax audio converter, although I see that the Book Lib Connect downloads the books in m4b format which I can play anyway, so no need to convert!  Many thanks again.

**Comment by audiamus** [comment]
> just to let you know I have installed Book Lib Connect, and despite some initial problems, it seems to work very well

Very good.

> I see that the Book Lib Connect downloads the books in m4b format 

Yes, that's the native format of Audible audiobooks, for both their aax and their aaxc variants. Book Lib Connect downloads aaxc. It's always a standard MP4 container with an encrypted audio stream. By convention, pure audio MP4 files are often called m4a or m4b, with m4a for music and m4b for audiobook, but the content is the same.  

Note that Book Lib Connect is only a downloader and decrypter, it neither touches meta data nor is it able to split a file. The original meta contains proprietary tags for several entries, like narrator name. And if you have a book with external chapter info, often with explicit chapter titles, not just numbers, the m4b output of Book Lib Connect wouldn't know about those. That's why the aax export feature exists. 

If AAX Audio Converter still asks for an activation code for an aax file from Book Lib Connect, any dummy code will do, e.g. 12345678.
