### ISSUE TITLE
explain differences between m4a and m4b 

### ISSUE THREAD

**Issue by PackElend** [audiamus/AaxAudioConverter#161]
Hi,
thx for the great app you saved my day today.
The only thing I'm still confused about is aax, m4a and m4b
In combination with https://github.com/audiamus/BookLibConnect I got

Export (by BookLibConnect) :
1. series_titles_B00ODBP0AW.json
2. What Do You Really W_B00O4DC0MK_LC_64_22050_Stereo.aax
3. B00O4DC0MK.json
4. content_metadata_B00O4DC0MK.json
Downloads (by BookLibConnect)
1. What Do You Really W_B00O4DC0MK_LC_64_22050_Stereo.m4b
Converted 
1. 
![image](https://user-images.githubusercontent.com/3542031/208650574-6b39f23e-7684-4880-b09d-b189c32c6092.png)

so do I still need [AaxAudioConverter](https://github.com/audiamus/AaxAudioConverter) ?

**Comment by audiamus** [comment]
> The only thing I'm still confused about is aax, m4a and m4b
Also include aaxc here. They are basically all MP4 container files, with - by convention - only with audio, no video. And the audio codec is typically AAC

m4a and m4b are plain audio MP4 and there is no difference at all between them, just convenience. Originally m4a stood for "**M**P**4** **A**udio" and nowadays is most often used for music. And then m4b was created for audio **b**ooks. In the beginning there was some confusion as some people claimed that m4b would support bookmarks which is incorrect. Bookmarks are a feature of the media player app not the audio file. I set the default in AAX Audio Converter to m4a because initially not all players were aware of the m4b file type. You can change that in the Basic Settings.

aax and aaxc are Audible proprietary naming conventions, the same MP4 container, but with an encrypted AAC audio stream. aax was the earlier encryption while aaxc is used today and is what Book Lib Connect downloads. aax, however, can also be unencrypted audio.

The Book Lib Connect export produces the same files as the now retired Audible app for Win10, so Book Lib Connect doesn't see a difference and had not to be adapted for Book Lib Connect.

> so do I still need AaxAudioConverter?

Book Lib Connect only downloads and decrypts the data, it does not touch the file in any other way. 

- Audible uses some custom tags for meta data which normal media players don't recognise. AAX Audio Conveter converts them to standard tags.
- The Book Lib Connect m4b file will have embedded chapters, but usually only with a chapter number, not with an explicit chapter name or title. (This appears to slowly change now with the most recent Audible releases.)  AAX Audio Converter can add the chapter names, if the accompanying json has them.
-  All the file splitting is handled by AAX Audio Converter. And even if you don't split the files but have a multipart download, you still get a playlist file added and AAX Audio Converter will try to delete the transition hints between the parts.
- MP3 conversion - if you need it - is only available with AAX Audio Conveter.

**Comment by PackElend** [comment]
@audiamus thx for all the information, now I know about m4a vs. m4b. I read a post, that m4b allows to store bookmarks etc., now it is corrected :). 


> * The Book Lib Connect m4b file will have embedded chapters, but usually only with a chapter number,

could be there any menu, which lists the chapter and allows the user to rename them?

**Comment by audiamus** [comment]
> could be there any menu, which lists the chapter and allows the user to rename them?

AAX Audio Converter does not show them in any GUI window, but will list them in the log file, both the embedded and the external ones (json).

With external software: Some players can list the chapters or at least navigate through them, like VLC (MP4 only) and MPC-HC (MP4 and MP3). MediaInfo also lists them (MP4 only). Things are rather complicated. There are two different standards for chapters in MP4 meta. And for MP3 there is very little for chapters at all, MPC-HC is one the exceptions. I'm not aware of any GUI software to alter chapters. FFmpeg can do it, but it's a console interface and you have to come up with a chapter file. And there are software libraries, of course. AAX Audio Converter uses one of them.

**Comment by PackElend** [comment]
thx again for the details :)

at least I can change 
![image](https://user-images.githubusercontent.com/3542031/209445355-9f51eded-be85-44b3-b4e3-76e1199d8e6d.png)
so the the files per chapter would be named as liked, aren't they?
![image](https://user-images.githubusercontent.com/3542031/209445398-730fd2ad-471e-430e-a145-5ca3670f73d9.png)

Would that also happen to the chapter in the metadata of the file, if only a single file is generated?
![image](https://user-images.githubusercontent.com/3542031/209445427-3610fb54-650f-4d2a-a882-724e22928ad6.png)

**Comment by audiamus** [comment]
> at least I can change ... so the the files per chapter would be named as liked, aren't they?

Yes, that will work. This json file is how the Audible Win 10 app extracted the extra chapter data. It's an Audible proprietary format but AAX Audio Converter can process it, replacingthe existing chapter data in the audio files with the external chapter data. The AAX Audio Converter manual has the details. Read also the sections on chapter marks and silence, because there may be discrepancies. 

Book Lib Connect downloads the extra chapter data from the Audible server and slightly adjusts the downloaded json to match the original Win 10 app format. 

> Would that also happen to the chapter in the metadata of the file, if only a single file is generated?

It will, if you enable it in the Basic Settings.
