### ISSUE TITLE
Single file per AAX file: Metadata track numbers for all tracks/chapters are set to "1"

### ISSUE THREAD

**Issue by RiseT** [audiamus/AaxAudioConverter#195]
Single file per AAX file: Metadata track numbers for all tracks/chapters are set to "1" instead of 1, 2, 3, ...

**Comment by audiamus** [comment]
I would need a log file here, log level 3.

**Comment by RiseT** [comment]
Here we go:

https://gist.github.com/RiseT/34641f56846c771756665b278432048a

**Comment by audiamus** [comment]
Thank you. According to the log, all chapter meta was written successfully to the audio file.

MPEG4 chapter data comes in two variants, "Nero" and "Quicktime". The external library ATL, which does all the meta work for AaxAudioConverter, writes both those variants. You could check the result with a tool like [MediaInfo](https://mediaarea.net/en/MediaInfo), independent of the player you normally use. MediaInfo should list both incarnations, if the chapters are present in the file.

**Comment by RiseT** [comment]
I'm using foobar2000 (which is very solid), will re-check with MediaInfo, though.

**Comment by RiseT** [comment]
MediaInfo shows the starting timestamps of the chapters, but no (metadata) track numbers.

**Comment by RiseT** [comment]
Loaded into foobar coming straight out of AAX Audio Converter:
![foobar 1](https://github.com/audiamus/AaxAudioConverter/assets/12624674/2fa85fbd-dba7-407f-9226-209167540cf7)

After applying foobars's Auto Track Number:
![foobar 2](https://github.com/audiamus/AaxAudioConverter/assets/12624674/c43c36dc-428c-4000-9dae-a31080848569)

**Comment by audiamus** [comment]
Sorry, big misunderstanding. I confused track and chapter numbers reading your post. 

This kind of track numbering that you see is by design. AaxAudioConverter associates track numbers with audio files. This allows some players to arrange multiple files in the right order, even without supporting a playlist. (For a few others that don't understand track tags, you have to set the option to create file names in alphanumerical order.) 

This concept means there will be exactly one track number per audio file. The track numbers are not related to chapter numbers. In single file mode you only get one track number, except for multi-part books where you get one track per part. In chapter mode you get one track per chapter, but track numbers and chapter numbers will only match for unnamed numeric ("generic") chapters. In split-chapter mode, there can be more than one track to a chapter. And in time-split mode, there can be more than one chapter per track.

**Comment by RiseT** [comment]
I see, many thanks for your detailed explanation.

> In single file mode you only get one track number, except for multi-part books where you get one track per part. 

Do you think this makes sense for single file mode? I mean, those players that don't support playlists (or even track tags) very likely neither support single audio files with embedded track information for multiple tracks (a. k. a. chapters with audio books). For multi-part books, the discnumber tag could be used, which results in the track number format seen in foobar above (i. e. 1.01, 1.02, 1.03, 2.01, 2.02, ...).

Just a thought.
