### ISSUE TITLE
New 'Enhanced Format'

### ISSUE THREAD

**Issue by greencardamom** [audiamus/AaxAudioConverter#24]
In a few weeks, Audible will switch to a proprietary 'Enhanced Format' only

https://goodereader.com/blog/audiobooks/audible-moving-to-enhanced-format-for-audiobooks

Will AaxAC be supporting it? I have an old-ish MP3 player that might not work with the new format.

**Comment by audiamus** [comment]
As as I understand it, they are retiring the rather old "Format 4". File extension would be .aa and internally, it's encrypted MP3. According to [wikipedia ](https://en.wikipedia.org/wiki/Audible_(store)), there have also been even older "Format 2" and "Format 3", with the same .aa file type, but I never have seen those. 

"Enhanced Format" appears to be their name for the .aax type file, already around for at least 10 years. This is an MPEG4 container with an encrypted AAC audio stream. And .aax files are the files AAX Audio Converter can convert, or more precisely, which FFmpeg can convert. This means we should be OK for the moment, until they announce to retire .aax as well.

(AAX Audio Converter should also be able to convert "Format 4" .aa files, but I only had a few samples, so that has not been thoroughly tested.)

**Comment by greencardamom** [comment]
Excellent, thank you! I use your app a lot so this is a big relief. I thought .aax was Format 4 and Enhanced was a new as yet seen type. They also say "a new software called AudibleSync" will replace Audible Manager, don't know if that could impact activation code retrieval.

**Comment by audiamus** [comment]
What we know at this time, there is a new format "aaxc", used in the mobile apps for Android and iOS, with reportedly different encryption. And there is the Audible App for Win10. This still downloads .aax. Is this the same as "AudibleSync"?
