### ISSUE TITLE
Ability to add multiple activation codes

### ISSUE THREAD

**Issue by Presjar** [audiamus/AaxAudioConverter#34]
Would it be possible to add support for multiple activation codes? I run multiple accounts I cycle through to take full advantage of the free trial months and other promotions. I have approx. 8 codes. Two accounts active at a time.

Would a possibility for this to work be to just brute force the provided activation codes against the AAX file until one is successful? Perhaps limit the number of codes allowable in the app to ~10 so it can help out people using this program against the own Audible library for legitimate purposes.

**Comment by audiamus** [comment]
Well, in a way this is a question of concept. And AAX Audio Converter deliberately takes a conservative approach here. 

Audible allowed multiple accounts with Audible Manager without having to sign in. With the Audible App, that's no longer the case, There can be only one active account and hence one activation code at a time. Since version 1.14 of AAX Audible Converter, you can switch your account in the Audible App without the need to close AAX Audio Converter in between.

And AAX Audio Converter allows you to add one custom activation code.

I'd rather leave this as it is.

**Comment by Presjar** [comment]
Switching the audible account from the Windows 10 audible app is very simple. I didn't realise that there was no need to relaunch AAX converter when swappning users. That will tech me to read all the change logs!

Your efforts are appreciated!
