### ISSUE TITLE
Some chapter titles missing from .m4b converted audiobook

### ISSUE THREAD

**Issue by twindagger** [audiamus/AaxAudioConverter#37]
I'm converting several of my audiobooks to .m4b at I've noticed that the chapter titles are missing from the later chapters in the book. All of the chapter titles are present in the metadata, but when using ffprobe after conversion you can see missing titles. I've attached a log file (level 4) and the output of ffprobe. I've tried this with "Verify and adjust chapter marks" set to "No" and "In all conversion modes" with the same result.
[AaxAudioConverter_2020-11-11_002.log](https://github.com/audiamus/AaxAudioConverter/files/5526034/AaxAudioConverter_2020-11-11_002.log)
[ffprobe-output.txt](https://github.com/audiamus/AaxAudioConverter/files/5526036/ffprobe-output.txt)

**Comment by audiamus** [comment]
Hmmh. The log file reports success. But it seems to only affect one of the two chapter variants. It may have to to with ATL.net, which is responsible for writing the chapters. 

What does MediaInfo say in tree view for "Menu 1" and "Menu 2"? 

Can you also try AAX Audio Converter 1.15.0? (You should uninstall first, otherwise the installer may refuse to downgrade). 1.15 uses ATL.net in unbuffered mode.

**Comment by twindagger** [comment]
MediaInfo Shows all of the chapters correctly in Tree view:
![Capture](https://user-images.githubusercontent.com/1916568/98867666-328a0880-242c-11eb-928d-a849f44f6ee9.PNG)

I tried with 1.15.0 and it does show all chapter names in both ffprobe and MediaInfo

**Comment by twindagger** [comment]
Here's the Menu #1 and #2 for 1.15.0

![Menu1](https://user-images.githubusercontent.com/1916568/98868236-0f138d80-242d-11eb-9afd-c315390b8900.PNG)
![Menu2](https://user-images.githubusercontent.com/1916568/98868242-1044ba80-242d-11eb-8105-67751740ef22.PNG)

**Comment by audiamus** [comment]
Thank you. 

So, I suggest to stick with 1.15.0 for the moment. Unless you want to do anything that is listed in the release notes for 1.15.1 and 1.15.2 you should be fine. 

I will try to reproduce the issue myself and then forward the matter to the [ATL.net](https://github.com/Zeugma440/atldotnet) project.

**Comment by twindagger** [comment]
Thanks, I'll stick with the earlier version for now.

**Comment by vi3itor** [comment]
Thanks for the great solution for converting my audiobooks. 

I tried to convert 2 books and I have a similar problem: in my case, all the chapters have the same name. I downgraded to 1.15.0 and everything works fine. 
Please let me know if you need any additional information (logs, or even files to reproduce the problem).

**Comment by audiamus** [comment]
I could reproduce the issue myself. It's caused by the current version 3.13 of ATL.net which introduced a new buffering strategy. Something may go wrong there. In version 1.15.0 I am using ATL.net the previous version 3.12 in unbuffered mode because the old buffering mode was allocating too much memory. Unbuffered mode requires much more disk I/O, so buffered mode is preferable.

I [reported ](https://github.com/Zeugma440/atldotnet/issues/75) it last week to the ATL.net project. It has already been acknowledged but the ATL.net author is currently busy with another task. "Stay tuned" he says. :relaxed:

**Comment by audiamus** [comment]
ATL.net published a new version with the fix yesterday. I have linked against this and just released the new version as 1.15.3.
