### ISSUE TITLE
AAX Audio Converter Stops Unexpectedly During Conversion

### ISSUE THREAD

**Issue by Sailfish** [audiamus/AaxAudioConverter#41]
Running AAC on two multi-part .aa files it stops unexpectedly during the conversion. I've attached the screenshot of AAC with the popup error message along with the -Log=3 log file.

![AACScreenCapture](https://user-images.githubusercontent.com/110050/102002952-57d19700-3cb6-11eb-8d4c-ccf8d366e309.jpg)
[AaxAudioConverter_2020-12-12_004.log](https://github.com/audiamus/AaxAudioConverter/files/5684178/AaxAudioConverter_2020-12-12_004.log)

**Comment by audiamus** [comment]
This log file doesn't match, I'm afraid. It is empty, apart from the startup sequence.

**Comment by Sailfish** [comment]
Regrettably, that's all that it logged. While I can't say for sure, I believe it aborted just as the **Convert** bottom bar completed. Before that, it was speeding along just fine. Is there another command line switch I might try that would provide more detail?

**Comment by audiamus** [comment]
Thank you. Not sure what happens here. According to AAX Audio Converter, all transcoding fails. This means that FFmpeg might do something but it does not produce any console output which AAX Audio Converter recognizes as successful completion.

Running it again, but this time with log level 4 might provide more clues. This will add all FFmpeg output to the log, making it much bigger. I recommend to compress the log file for uploading.

A possible explanation could be that FFmpeg cannot decode the file, perhaps because it is in an older format, not "Format 4" as expected. We will see.  

> Another odd thing is that the conversion had 39 steps instead of 37 after doing that.

That is because of the additional file copying. I don't think it has anything to do with the log file. As a precaution, do not open the current log file in an editor while the AAX Audio Converter session is running. This may prevent log entries to be written. If you want to monitor the log, use a tool that opens the file read-only, like LogExpert.

**Comment by Sailfish** [comment]
**audiamus:** _Run the following command from a console window:
                <path to>\ffmpeg.exe -hide_banner -i <offending file>.aa 2> out.txt
                FFmpeg.exe will be in the same folder as AAXAudioConverter.exe.
                One of the problematic files appears to be DeadSixPart3_mp332_ARKLXNBG8DW1U.aa_
I ran AAC on both the KingsLeaguePart1.aa and the DeadSixPart3.aa files and have attached each of the out files for your evaluation.

**Raudiamus:** _Run the original AAX Audio Converter session again, but this time with log level 4 and let's see how and if FFmpeg will be involved._

[DeadSixPt3Out.txt](https://github.com/audiamus/AaxAudioConverter/files/5684990/DeadSixPt3Out.txt)
[KingsLeaguePt1Out.txt](https://github.com/audiamus/AaxAudioConverter/files/5684991/KingsLeaguePt1Out.txt)

**audiamus:** _Running it again, but this time with log level 4 might provide more clues. This will add all FFmpeg output to the log, making it much bigger. I recommend to compress the log file for uploading._

[DeadSixPt3Out.txt](https://github.com/audiamus/AaxAudioConverter/files/5684990/DeadSixPt3Out.txt)
[KingsLeaguePt1Out.txt](https://github.com/audiamus/AaxAudioConverter/files/5684991/KingsLeaguePt1Out.txt)

I've attached the ZIP'd log file log file from the log level 4 of KingsLeaguePart1
[AaxAudioConverter_2020-12-13_001KingsLeaguePart1.zip](https://github.com/audiamus/AaxAudioConverter/files/5684994/AaxAudioConverter_2020-12-13_001KingsLeaguePart1.zip)

**Comment by Sailfish** [comment]
[AaxAudioConverter_2020-12-13_001KingsLeaguePart1.zip](https://github.com/audiamus/AaxAudioConverter/files/5689333/AaxAudioConverter_2020-12-13_001KingsLeaguePart1.zip)

Here's the ZIP'd level 4 file, per your request.

**Comment by audiamus** [comment]
Thank you.

FFmpeg reports many errors here. It's hard to tell what exactly goes wrong, but FFmpeg is not able to convert these two files, with "invalid" messages right from the first packet. Since both behave the same way, I don't think the files are corrupt. How old are these? If they are "Format 3" or "Format 2", and not "Format 4", then FFmpeg cannot handle them, as far as I know.

I understand that several others of your .aa files were converted successfully?

**Comment by Sailfish** [comment]
While I do have some AA titles that are old, all of them are Format 4. As for this title, I've attached a filelist that provides the date of download along with a screenshot of AudibleManager depicting its Format 4 title type.
![Kings League AudibleManager screenshot](https://user-images.githubusercontent.com/110050/102142523-64b9cc00-3e17-11eb-8ad7-0778a341fb45.jpg)

![Kings League File List](https://user-images.githubusercontent.com/110050/102142092-b44bc800-3e16-11eb-81b4-dba0eef90072.jpg)

**Comment by Sailfish** [comment]
Audiamus: I understand that several others of your .aa files were converted successfully?

[AaxAudioConverter_2020-12-14_003.zip](https://github.com/audiamus/AaxAudioConverter/files/5692457/AaxAudioConverter_2020-12-14_003.zip)
[AbaddonsGatePt1Out.txt](https://github.com/audiamus/AaxAudioConverter/files/5692458/AbaddonsGatePt1Out.txt)
![AAC_aa_SuccessfulConversionFilelist](https://user-images.githubusercontent.com/110050/102153820-e5cf8e00-3e2c-11eb-812a-a3f4fab483de.jpg)
![AAC_aa_TitleSuccessfulConversion](https://user-images.githubusercontent.com/110050/102153828-ebc56f00-3e2c-11eb-8d20-827318a67aaa.jpg)

Yes, I ran your AAC on one of them and attached the following:
- level 4 ZIP'd log
- FFmpeg output on Pt1
- screenshot of the converted files
- screenshot of your AAC conversion results.

I hope  will help your analysis

**Comment by audiamus** [comment]
I am totally in the hands of FFmpeg here. If FFmpeg says, it can't read the audio, then that's it for this file, I'm afraid.

The FFmpeg documentation doesn't give a clue, either. Conversion works for some, but apparently not for all.

**Comment by Sailfish** [comment]
Okay, seeing how fast the aax transcoding work versus .aa, I have already decided to go ahead and download the aax version for all author titles I have flagged as worth listening to again. With well over 1000 titles, and most of them flagged as worthy, that will be a daunting task but one, ultimately, be worth it.

Thanks for your time on this.
