### ISSUE TITLE
Support for AAXC Files

### ISSUE THREAD

**Issue by DianoteHD** [audiamus/AaxAudioConverter#84]
I have all Books already on my phone.
The files aren't named like the book but have a .aaxc extention. 
Also there is a .companion file for every book.

AAXC Files are now not supported with your converter but maybe they could?
Also there could be a usage for the .companion file.

**Comment by audiamus** [comment]
For the time being I recommend to re-download your books with the Audible App for Win 10 so that you get them in .aax format.

.aaxc is a very different format. To decode it with non-Audible software any such 3rd party app would need direct online access to your Audible account, including your Audible/Amazon password. Even if such software would do everything to protect the user's credentials - and not save and reuse the password - it still requires a lot of user trust.

I will not rule out that AAX Audio Converter supports such a direct online access mechanism in the future, but its usage will always be optional.

**Comment by DianoteHD** [comment]
okay, it's just something i found last night and thougt it could be useful
