### ISSUE TITLE
Endpoint Protection triggers

### ISSUE THREAD

**Issue by fsiep** [audiamus/AaxAudioConverter#92]
Hi,

The app when using it to convert a AAX file triggers Endpoint Protection. The app seems to manipulate Crashpad/Settings.dat and Explorer/Iconcache.dat files. Not sure what that means but I never had anything like that before. Why is that?

Thank you!

**Comment by audiamus** [comment]
This sounds like a configuration setting on your computer. If you let AAX Audio Converter associate itself with AAX files, so that double-clicking an AAX file will then launch the app, a few Win32 system calls are made which add AAX Audio Converter to the Windows Registry. In this context the app icon will probably be stored in a cache. But that is beyond the control of AAX Audio Converter.
